# CDN server
location:

# style
style:
  scheme: '1'
  bg_img: /img/bg.png
  avatar: /img/avatar.png
  slogan: "I'm your slogan!"
  hoverable: true

# HTML head
head:
  favicon: /img/favicon.png
  high_res_favicon: /img/favicon.png
  apple_touch_icon: /img/favicon.png
  keywords: blog, hexo, mdui

# color
color:
  primary_color: "indigo"
  accent_color: "blue"
  layout:
  random:

# appbar
appbar:
  title: "Title"

# post settings
post:
  entry_excerpt: 80
  # topPost: true
  donate:
    wechat: /img/avatar.png
    paypay: 'https://paypal.com'

share_menu: #false
  rss: false
  weibo: false
  twitter: true
  facebook: true
  googleplus: true
  linkedin: true
  qq: false
  telegram: false

qr_code: false

comment:
    use:
    shortname:
    provider:

# pagination
# github@zllovesuki
index:
  show: 2

# footer
footer:
  since:
  ICP:

# Plugins
busuanzi: #false
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

service_woker: 'pwa'

pages:
  Test1:
    link: "/myfriends"
    icon: "&#xe0ba;"
  Test2:
    link: "/apply-for-link"
    icon: "&#xe7f0;"
  Test3:
    link: "/timeline"
    icon: "home"

sns:
  Twitter: https://twitter.com
  Facebook: https://facebook.com

# Translations
translations:
  # archive: 'Archive'
  archives: 'Archives'
  category: 'Category'
  categories: 'Categories'
  index: 'Index'
  pages: 'Pages'
  tag: 'Tag'
  tags: 'Tags'
  years: 'Years'
  go_to_prev_page: 'Return'
  busuanzi_views: 'Views: '
  footer:
    contact_me: 'Contact me'
    how_to_contact_me: 'How to contact me'
    close: 'Close'
  share_menu:
    rss: 'Article RSS'
    facebook: 'Share to Facebook'
    googleplus: 'Share to Google+'
    linkedin: 'Share to Linkedin'
    qq: 'Share to QQ'
    telegram: 'Share to Telegram'
    twitter: 'Share to Twitter'
    weibo: 'Share to Weibo'
  snackbar: 'Oops! Nothing happened.'
  donate: 'Buy me a beer?'
  comments: 'Comments'
  outdated_browser:
    title: 'Your browser is out-of-date!'
    line_one: 'Update your browser to view this website correctly. '
    link: 'Update my browser now '
    close: 'Close'

# Vendors
vendors:
  mdui_min_css:
  mdui_min_js:
  style_min_css:
  js_min_js:
