
# html lang
language: zh-CN

# Head info
head:
    favicon: "/img/favicon.ico"
    high_res_favicon: "/img/favicon.ico"
    apple_touch_icon: "/img/favicon.ico"
    keywords:
    hitokoto: "lwl12"


dynamic_title: "喵喵喵"

appbar:
  fixed:
    enable: true
    scroll_hide:

userview:
  avatar: "/img/avatar.png"
  bgimg: "/img/bg.png"
  email: "example@example.com"

# text_color = theme, red, red-900
drawer:
  accordion: "false"
  subtitle: "????"
  holiday:
    enable: true
    text:
      - "新年快乐！"
      - "在此Halyul祝您鸡年大吉！"
    text_color: "red"
    bg_color:
  counter:
    enable: true
    date: 12/29/2016 23:00:00
    progress_bar: true
  menu:
    homepage:
      icon: "&#xe88a;"
      title: ""
      circle: true
      color: "red"
      fix:
      text_color:
      bg_color:
    archives:
      enable: true
      icon: "&#xe156;"
      title: ""
      circle: true
      color: "red"
      arrow:
      fix: true
      text_color:
      bg_color:
    categories:
      enable: true
      icon: "&#xe86d;"
      title: ""
      circle: true
      color: "red"
      arrow:
      fix: true
      text_color:
      bg_color:

pages:
    list:
      Todo List:
        link: "/todo"
        icon: "&#xe86d;"
        circle: true
        color: "red"
        fix:
        text_color:
        bg_color:
      TEST:
        link: "/todo"
        icon: "&#xe86d;"
        circle: true
        color: "red"
        fix:
        text_color:
        bg_color:
      Tag Cloud:
        link: "/tags"
        icon: "&#xe892;"
        circle: true
        color: "red"
        fix:
        text_color:
        bg_color:

    collapse:
      Todo List:
        links:
          test1:
            link: "/test"
            text_color:
            bg_color:
          test2:
            link: "/test2"
            text_color:
            bg_color:
        icon: "&#xe86d;"
        circle: true
        color: "red"
        arrow:
        fix: true
        text_color:
        bg_color:
      TEST:
        links:
          test1:
            link: "/test"
            text_color:
            bg_color:
          test2:
            link: "/test2"
            text_color:
            bg_color:
        icon: "&#xe86d;"
        circle: true
        color: "red"
        fix: true
        text_color:
        bg_color:

background:
  color:
  img:

typinyin:
  title: true

theme:
  layout:
  primary_color: indigo
  accent_color: indigo
  chang_theme: true

pace:
  style: center-atom
  color: "#3F51B5"

smoothscroll: true

# 文章上一页有问题
fab:
  trigger: "hover"
  main:
    first_icon: "&#xe145;"
    second_icon: "&#xe14c;"
  top:
    color: "pink"
    icon: "&#xe316;"
  prev:
    color: "red"
    icon: "&#xe314;"
  next:
    color: "orange"
    icon: "&#xe315;"

index_head_left:
  userview: "bottom"
  title: "img-bottom"
  gradient: ""
  slogan: "<script>lwlhitokoto()</script>"
  img: "https://api.i-meto.com/bing"
  subtitle: "Never do a dreamer"

index_head_right:
  userview: "bottom"
  gradient: ""
  img: "/img/logo.png"
  subtitle: "Never do a dreamer"

# userview: "top", "bottom", "center"
# title: "img-top", "img-bottom", "card-center", "card-top"
post:
  userview: "bottom"
  title: "img-bottom"
  gradient: ""

qrcode: true

copyright:
  blog_start_year: "2016"

sns:
  Email:
    link: "mailto:halyul@halyul.cc"
  并不存在的Facebook:
    link: "www.facebook.com/halyul"
  Github:
    link: "github.com/halyul"
  404的Google Plus:
    link: "plus.google.com/u/0/109529410449534581819"
  链接已重置的Twitter:
    link: "twitter.com/HalyulXu"
  我的微博:
    link: "weibo.com/halyul"



# 文章和评论分开放 用tab选项卡/底部导航栏
# 路径指示器
# 卡片缩略图有问题
# 恢复默认主题有BUG
# 文章卡片颜色自定义
# index_head_left添加slider样式, 更换title subtitle样式（用viosey主题
# 卡片悬浮
