# html lang
language: en

# HTML head
head:
  favicon: /img/favicon.png
  high_res_favicon: /img/favicon.png
  apple_touch_icon: /img/favicon.png
  keywords:

# color
color:
  primary_color: "indigo"
  accent_color: "blue"
  layout:

# appbar
appbar:
  title: "TITLE"

# post settings
post:
  avatar: /img/avatar.png
  entry_excerpt: 50

share_menu: #false
  weibo: true
  twitter: true
  facebook: true
  googleplus: true
  linkedin: true
  qq: true
  telegram: true

qr_code:

comment:
    use:
    shortname:
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
# pagination
# github@zllovesuki
index:
  show: 2

# footer
copyright:
  start_year: 2016

# Plugins
busuanzi: #false
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

pages:
  Test1:
    link: "test1"
    icon: "&#xe84d;"
  Test2:
    link: "test1"
    icon: "&#xeb3b;"
  Test3:
    link: "test1"
    icon: "&#xe851;"

sns:
  Twitter: "https://twitter.com"
  Facebook: "https://facebook.com"

# Translations
translations:
  archive: 'Archive'
  archives: 'Archives'
  category: 'Category'
  categories: 'Categories'
  index: 'Index'
  pages: 'Pages'
  tag: 'Tag'
  tags: 'Tags'
  years: 'Year'
  busuanzi_views: 'Views: '
  footer:
    contact_me: 'Contact Me'
    how_to_contact_me: 'How to contact me'
    close: 'close'
  share_menu:
    facebook: 'Share to Facebook'
    googleplus: 'Share to Google+'
    linkedin: 'Share to Linkedin'
    qq: 'Share to QQ'
    telegram: 'Share to Telegram'
    twitter: 'Share to Twitter'
    weibo: 'Share to Weibo'
