# CDN for mathjax
location:

# style
style:
  scheme: 'now'
  bg_img: /img/bg.png
  avatar: /img/avatar.png
  slogan: "I'm your slogan!"
  hoverable: true

# HTML head
head:
  favicon: /img/favicon.png
  high_res_favicon: /img/favicon.png
  apple_touch_icon: /img/favicon.png
  keywords: blog, hexo, mdui

# color
color:
  primary_color: "indigo"
  accent_color: "blue"
  layout:
  random:
  bg_color: "#eeeeee"

# appbar
appbar:
  title: "Title"
  search: false

index:
  welcome: "Welcome to my blog~"
  notification: false

# post settings
post:
  entry_excerpt: 80
  qr_code: true
  prism:
    theme:
    line_number:
  donate:
    wechat:
      link: /img/avatar.png
      fa: 'fa-wechat'
    paypay:
      link: 'https://paypal.com'
      fa: 'fa-paypal'
  license:
    name: 'CC BY-NC-SA 4.0'
    link:  'https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh'

share_menu: false
#  rss: false
#  weibo: false
#  twitter: true
#  facebook: true
#  googleplus: true
#  linkedin: true
#  qq: false
#  telegram: false

comment:
    use:
    shortname:

# pagination
# github@zllovesuki
pagination: 2

# footer
footer:
  since:
  ICP:
  image:

# Plugins
busuanzi:  false
#  all_site_uv: true
#  post_pv: true
#  busuanzi_pure_mini_js: "//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

service_woker:

about_me: false

pace: false

random_pics: 44

pages:
  Test1:
    link: "/myfriends"
    md: "&#xe0ba;"
  Test99:
    link: "/myfriends"
    md: "&#xe0ba;"
  Test8:
    link: "/myfriends"
    md: "&#xe0ba;"
  Test877:
    link: "/myfriends"
    md: "&#xe0ba;"
  Test8234:
    link: "/myfriends"
    md: "&#xe0ba;"
  Test2:
    link: "/apply-for-link"
    fa: "fa-child"
  Test3:
    link: "/timeline"
    md: "home"
  Test4:
    cascade: true
    md: 'home'
    pages:
      TEST1:
        link: "/myfriends"
        md: "&#xe5ca;"
      TEST2:
        link: "/timeline"
        md: "home"
      Test3:
        link: "/timeline"
        md: "home"

sns:
  Twitter:
    link: https://twitter.com
    fa: 'fa-twitter'
  Facebook:
    link: https://facebook.com
    null_icon: true
  TEST:
    link: https://facebook.com
    md: "&#xe168;"
  TEST1:
    link: https://facebook.com

# Vendors
vendors:
  fonts_min_css:
  style_min_css:
  js_min_js:
  outdatedbrowser_min_js:
  pace_min_js:
  pace_style_css:
